[package]
name = "compare_baseline"
version = "0.1.0"
edition = "2021"

[dependencies]
madvr_parse = "1.0.2"
clap = { version = "4.5.4", features = ["derive"] }
anyhow = "1.0.86"
itertools = "0.13.0"
